### ISSUE TITLE
Installers For Daedalus For Incentivised Testnet

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr-ops#11]
https://iohk.myjetbrains.com/youtrack/issue/DDW-979

**Comment by gmanroney** [comment]
Would like to know when installers for windows, linux and macos ready for Daedalus

**Comment by disassembler** [comment]
This is related to daedalus and not deployment with jormungandr-ops. issue is tracked in YT per daedalus team (linked above).
