### ISSUE TITLE
Integrate Auto-Generated Network Yaml File With Testnet Site

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr-ops#13]
- We need to work with website team so that when we generate a new YAML file for the network the correct values are reflected in the site. 

- Ops team needs to explain data dictionary, where YAML file can be found and confirm what is 'pulled' into the site is correct. 

- Site team also need guidance on how often to poll the file for updates.

**Comment by disassembler** [comment]
resolved
