### ISSUE TITLE
Jormungandr v0.7.0-rc6 to QA Cluster & Nightly

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/jormungandr-ops#25]
**Environment**
QA & Nightly

**Version**
https://github.com/input-output-hk/jormungandr/releases/tag/v0.7.0-rc6

**Additional Details**
Can you kindly provide us with an updated config.yaml and genesis hash (if required)?
Thanks in advance, you guys rock (*again!*)! :)

**Comment by NicolasDP** [comment]
No need for new genesis hash! both are compatible with each others

**Comment by alan-mcnicholas** [comment]
Can you hold off on upgrading Nightly until Sam gives it the green light also? Thanks again!

**Comment by manveru** [comment]
QA was upgraded, but it didn't really improve behavior.
