### ISSUE TITLE
Funds from QA faucet does not get to requester

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#29]
**Description**
Funds from QA faucet does not get to requester even the request to the faucet endpoint is successful.

**Steps to reproduce**
1. my node is synced
2. ```
$ curl -X POST https://faucet.qa.jormungandr-testnet.iohkdev.io/send-money/ca1s4k0uucdt73tv5tduswxe6q6dra206u9v53ntpqh9zx5j6v7a3pjgxr9vf6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    407      0 --:--:-- --:--:-- --:--:--   406{"success":true,"amount":1000000000000,"fee":1100,"txid":"4960fcb4903bc89cae8300466c23f863dd31b8ead362457ee24dd6797a7e10e0"}
```
3. wait for 1 new block to be created/received
4. ```
$ jcli rest v0 account get ca1s4k0uucdt73tv5tduswxe6q6dra206u9v53ntpqh9zx5j6v7a3pjgxr9vf6 --host "http://127.0.0.1:9000/api"
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:9000/api/v0/account/6cfe730d5fa2b6516de41c6ce81a68faa7eb856523358417288d49699eec4324: Client Error: 404 Not Found
```

**Criteria for resolution**
Requested funds can be seen in the requester's balance.

**Comment by manveru** [comment]
This also seems resolved after making sure the faucet has enough funds now.
