### ISSUE TITLE
Nodes required for Live website release

### ISSUE THREAD

**Issue by pkellyiohk** [input-output-hk/jormungandr-ops#31]
**Task**
We (Agency) need a node on both https://shelley-testnet-explorer-qa.netlify.com/ & https://shelleyexplorer.cardano.org running the build we intend to use for release (so we stop using our own self node)

**Time Line**
ASAP

**Additional Details**
Please contact @robert.moore on Slack for more info.

**Comment by lewnelson** [comment]
Can we also have this node be accessible from `https://shelley-testnet-explorer-staging.netlify.com/ ` potentially even `https://*--shelley-testnet-explorer-staging.netlify.com/ ` if possible as we have deployment previews for PR's which end up on subdomains like `https://5dc59cc210d8e2000845270f--shelley-testnet-explorer-staging.netlify.com/ `.

And also on `https://shelley-testnet-explorer.netlify.com/`

**Comment by iamrobertmoore** [comment]
This was done, I can't close it though.
