### ISSUE TITLE
Faucet Down on Nightly Network

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr-ops#32]
**Description**
the faucet for nightly network seems to be down, should it be? Where should we report this kind of issue?
Last login: Mon Nov 11 13:54:00 on ttys000
Carls-MacBook-Pro:~ carl$ curl -X POST https://faucet.nightly.jormungandr-testnet.iohkdev.io/send-money/Aca1s4ffyuut9ahxq404g02qvc4d8450cw9t2zf6cm5dc0yh4r2rzqsejkes5mv
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Steps to reproduce**
Same comand run by Alejandro and Taro same result.

**Criteria for resolution**

**Comment by manveru** [comment]
The URL was at `https://jormungandr-faucet.*` instead of `https://faucet.*`, It's fixed now.

**Comment by dorin100** [comment]
The faucet is responding with `Success` but the funds are not received by the address:
```
$ curl -X POST https://faucet.nightly.jormungandr-testnet.iohkdev.io/send-money/ca1skrcc3lr7wp2esytww92j56rpxq4rvnxel7mzqsx4t4ucae8dvnvx8ncqav
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    521      0 --:--:-- --:--:-- --:--:--   521{"success":true,"amount":10000000000,"fee":1100,"txid":"6504f159a39f45f0da779f8b08fa2fdf0eb2b896a0019d41cfffc32e71d677fc"}
```

```
$ jcli rest v0 account get ca1skrcc3lr7wp2esytww92j56rpxq4rvnxel7mzqsx4t4ucae8dvnvx8ncqav --host "http://127.0.0.1:9000/api"
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:9000/api/v0/account/878c47e3f382acc08b738aa95343098151b266cffdb10206aaebcc77276b26c3: Client Error: 404 Not Found
```

**Comment by disassembler** [comment]
Duplicate issue, and resolved
