### ISSUE TITLE
Updated Genisis hash and Config Node files missing for v0.7.0

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr-ops#36]
**Description**
https://hydra.iohk.io/job/Cardano/jormungandr/jormungandrConfigs.nightly/latest points to https://hydra.iohk.io/build/1334642 which was Finished at: | 2019-11-08 19:51:57. Since v0.7.0 was released with breaking changes I expect to find new Genesis hash and Config info. 

Maybe my assumption is incorrect. 

**Steps to reproduce**
1. Do something
2. Do something else
3. It breaks

**Criteria for resolution**

**Comment by disassembler** [comment]
There was about an hour or so gap of me pushing all the environment changes from the time we reset the cluster. This was on purpose as we were validating things internally across 3 environments at the same time before releasing them to the public. It was publicly announced and managed communications in telegram. It was a reported maintenance of shutting down the networks.
