### ISSUE TITLE
JSON file for Incentivised Testnet Daedalus installers

### ISSUE THREAD

**Issue by iamrobertmoore** [input-output-hk/jormungandr-ops#39]
**Task**
The webdev team (robert.moore) require a JSON file to include download links, file refs & hash's for the Daedalus installers to use on the incentivised testnet. For ease, suggest structuring this identically to the Byron JSON file as we have been building ancitipating this structure anyway.

**Time Line**
Today 13/11.

**Comment by disassembler** [comment]
This is resolved. We used this Thursday for release and usage has been internally documented.
