### ISSUE TITLE
QA Faucet does not work - 0.7.0

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#43]
**Description**
QA Faucet does not work

**Steps to reproduce**
$ curl -X POST https://faucet.qa.jormungandr-testnet.iohkdev.io/send-money/ca1shfgt2t4v3cdt8h67ysh05wk5p66f6lf4wm0zk7tn75s7fpumf7sq48h0pw
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    26    0    26    0     0    164      0 --:--:-- --:--:-- --:--:--   163500 Internal Server Error

**Criteria for resolution**
Request from the faucet is successful and funds are received by the requestor.

**Comment by disassembler** [comment]
We wrote a new faucet Thursday/Friday because of these breaking changes and lack of error handling in the J's chain libs faucet. This is resolved now.
