### ISSUE TITLE
UI faucet for Beta testnet does not work

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#51]
**Description**
UI faucet for Beta testnet returns error.

**Steps to reproduce**
1. open fauct UI for beta testnet - https://testnet.iohkdev.io/en/cardano/shelley/tools/faucet/
2. request funds for an account address - `ca1s5pdthcrsj0jj7mqp4zp4ehcn7ser3svhrmhsk4nrertdz8hp2vs7ap9wn3`

**Criteria for resolution**
- no error is seen and funds are received by the address

![image](https://user-images.githubusercontent.com/29144964/69617001-36b4ee80-1040-11ea-826d-ef47c98a0cce.png)

**Comment by iamrobertmoore** [comment]
For a little context, nothing has changed on the front end site (but we can change something if needs be). 

It seems likely a devops issue given @manveru comment that 'i rewrote the faucet a while ago and it might not be 100% compatible yet'
