### ISSUE TITLE
Requesting rolling restart on Incent TestNet

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/jormungandr-ops#56]
**Task**
Rolling restart of our hosted nodes within the Incentivized TestNet

**Time Line**
asap

**Additional Details**
The sync times have crept back up (I am still at 0% after ~15 minutes) making Daedalus unusable for any users who wish to still check their balance was imported successfully. Many thanks!

**Comment by manveru** [comment]
In progress...

**Comment by alan-mcnicholas** [comment]
Would it be possible to create a chron job for this task? The slowdown seems to occur pretty much daily and by the time we have discovered it then it has already become a problem for end users. This may be overly complex and if so please disregard and we can stick with the manual approach! :)
