### ISSUE TITLE
Requesting deployment of 0.8.0rc3 to Nightly Testnet

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr-ops#60]
**Environment**
Nightly

**Version**
0.8.0-rc2

**Additional Details**

- [x] reset the blockchain (with a new block start date, as I am sure you already do anyway)
- [x] use everything as in #59 

release notes are there: https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.0-rc3

**Comment by manveru** [comment]
Release is out, new hash/trusted peers at: https://github.com/input-output-hk/iohk-nix/blob/1033da6c964a834980444b2c094b15f89fc1701c/jormungandr-lib/default.nix#L187-L222
