### ISSUE TITLE
Please deploy 0.8.0-RC4 on Nightly and QA testnets

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#61]
**Environment**
Nightly and QA

**Version**
https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.0-rc4

**Additional Details**
Thank you!

**Comment by manveru** [comment]
https://github.com/input-output-hk/iohk-nix/pull/257 is in the pipeline

**Comment by manveru** [comment]
Deployed to both networks.
