### ISSUE TITLE
Please deploy 0.8.0 to QA and Nightly

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#77]
**Environment**
QA, Nightly

**Version**
https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.0

**Additional Details**
https://input-output-rnd.slack.com/archives/GJJSXM010/p1576068782245300?thread_ts=1576068046.243100&cid=GJJSXM010

**Comment by alan-mcnicholas** [comment]
Can we use the following parameters
