### ISSUE TITLE
Faucet Empty

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr-ops#79]
https://iohk.zendesk.com/agent/tickets/75441

**Comment by carl-IOHK** [comment]
https://iohk.zendesk.com/agent/tickets/74874

**Comment by carl-IOHK** [comment]
Resolved problem https://iohk.zendesk.com/agent/tickets/75472

**Comment by manveru** [comment]
Wallet rotated, faucet works again.
