### ISSUE TITLE
Faucet Rest API endpoint for nightly release does not provides funds

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#8]
Even it displays a success message, the transactions are remaining in pending and the funds are not received by the account

```
C:\Users\Dorin>curl -X POST https://jormungandr-faucet.jormungandr-testnet2.iohkdev.io/send-money/ca1s4066aa45luj8w2xa3xqakl0fj3ka2l56ca8vcpzwrfxmhmsz6pfkamc34c
{"success":true,"amount":10000000000,"fee":1100,"txid":"6821fe1320f155d468a96b6367b321efb83c03151773b9fbb871453a846661d6"}
```

```
- fragment_id: 6c0fe6473838d3b2b37756bf8edd171e9b7ce61ac6509ca6e559dde44c8f0e05
  last_updated_at: "2019-10-25T07:43:02.019647800+00:00"
  received_at: "2019-10-25T07:43:02.019647800+00:00"
  received_from: Network
  status: Pending
```

```
C:\Users\Dorin>jcli rest v0 node stats get --host "http://127.0.0.1:9000/api"
---
blockRecvCnt: 499
lastBlockDate: "4.559"
lastBlockFees: 0
lastBlockHash: dc23c4fa50074d7a57961eb6f8a028800382f0239f0c9a61e18199e6c3e94d66
lastBlockHeight: "1979"
lastBlockSum: 0
lastBlockTime: "2019-10-25T07:43:07+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 4
uptime: 1390
```

Michael Fellinger  -> `there is simply no propagation between the relays and stake nodes`

**Comment by dorin100** [comment]
it seems that there was a version mismatch (an older version on testnet). nodes updated and everything is ok now

**Comment by dorin100** [comment]
It seems that I was able to receive funds from faucet only at the first request I made.

**Comment by disassembler** [comment]
We've finalized the investigation and can confirm there are issues upstream in jormungandr in this release. Blocks are failing to relay to stake pools as witnessed by the higher level of transactions listed on relays vs the stake pools in the graphs. Also, stake-apn1 keeps losing sync and any blocks adopted on it are rolled back. All nodes aside from stake-apn1 are fully in sync, yet faucet requests still fail. Upstream issue: https://github.com/input-output-hk/jormungandr/issues/1031

**Comment by disassembler** [comment]
This is not an issue releated to deployment. Please follow progress in input-output-hk/jormungandr#1031
