### ISSUE TITLE
Please deploy v0.8.1 to QA and Nightly

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/jormungandr-ops#84]
**Environment**
QA, Nightly

**Version**
https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.1

**Additional Details**
This should be a straight forward upgrade with no breaking changes listed.
Can we set `rewards_drawing_limit_max` parameter to `4109589/10000000000` rather than `15/100`
Thanks again, you guys rock!!

**Comment by manveru** [comment]
This is deployed now
