### ISSUE TITLE
faucet

### ISSUE THREAD

**Issue by z6586** [input-output-hk/jormungandr-ops#87]
curl -X POST https://faucet.nightly.jormungandr-testnet.iohkdev.io/send-money/addr1skglt882gkfpjuacsx6kujeqpu6xjk3nrn2qj4atvd7wfwaf3la9x2vzn78
{"statusCode":429,"error":"Too Many Requests","message":"Try again in 24070 seconds","retryAfter":

help 
jormungandr -V

jormungandr 0.8.3

**Comment by manveru** [comment]
This behaves as expected, there is a limit to how often you can request funds from the faucet.

**Comment by z6586** [comment]
thanks
