### ISSUE TITLE
Please deploy v0.8.5-alpha3 to nightly and QA

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr-ops#90]
**Environment**
QA, nightly

**Version**
v0.8.5-alpha3

**Additional Details**
Upgrade
https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.5-alpha3

**Comment by johnalotoski** [comment]
Deploy to QA on v0.8.5-alpha3 completed.
