### ISSUE TITLE
api/rewards/epoch/44 is not returning anything

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr-ops#98]
**Description**
Even all 3 explorer nodes are up, I cannot take the rewards for the previous epoch - 44 --> https://explorer.incentivized-testnet.iohkdev.io/api/rewards/epoch/44

**Steps to reproduce**
1. Run https://explorer.incentivized-testnet.iohkdev.io/api/rewards/epoch/44

**Criteria for resolution**

**Comment by manveru** [comment]
Restarting the explorer nodes fixed this.
